---
version: '3.5'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres:12
    restart: always
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=HOPSIIA
    volumes:
     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: